export const weatherApiData = {
  queryCost: 1,
  latitude: 51.5064,
  longitude: -0.12721,
  resolvedAddress: 'London, England, United Kingdom',
  address: 'london',
  timezone: 'Europe/London',
  tzoffset: 1,
  description: 'Similar temperatures continuing with no rain expected.',
  days: [
    {
      datetime: '2023-08-10',
      datetimeEpoch: 1691618400,
      temp: 15.7,
      feelslike: 15.7,
      humidity: 75,
      dew: 10.8,
      precip: 0.2,
      precipprob: 100,
      snow: 0,
      snowdepth: 0,
      preciptype: ['rain'],
      windgust: 15.8,
      windspeed: 12.8,
      winddir: 268.6,
      pressure: 1021,
      cloudcover: 59.5,
      visibility: 12.3,
      solarradiation: 411.5,
      solarenergy: 35.4,
      uvindex: 10,
      severerisk: 10,
      conditions: 'Rain, Partially cloudy',
      icon: 'rain',
      stations: ['EPKT', 'E9997', 'EPKK', 'E6527'],
      source: 'comb',
      tempmax: 20.9,
      tempmin: 11.9,
      feelslikemax: 20.9,
      feelslikemin: 11.9,
      precipcover: 4.17,
      sunrise: '05:21:46',
      sunriseEpoch: 1691637706,
      sunset: '20:08:43',
      sunsetEpoch: 1691690923,
      moonphase: 0.8,
      description: 'Partly cloudy throughout the day with early morning rain.',
      hours: [
        {
          datetime: '00:00:00',
          datetimeEpoch: 1691618400,
          temp: 13.9,
          feelslike: 13.9,
          humidity: 93.69,
          dew: 12.9,
          precip: 0.2,
          precipprob: 100,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 13,
          windspeed: 12.8,
          winddir: 250,
          pressure: 1019,
          cloudcover: 87.4,
          visibility: 9.8,
          solarradiation: 2,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Rain, Partially cloudy',
          icon: 'rain',
          stations: ['EPKT', 'EPKK', 'E6527'],
          source: 'obs',
        },
        {
          datetime: '01:00:00',
          datetimeEpoch: 1691622000,
          temp: 13.9,
          feelslike: 13.9,
          humidity: 87.92,
          dew: 11.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 13.7,
          windspeed: 9.3,
          winddir: 250,
          pressure: 1019,
          cloudcover: 88.2,
          visibility: 9.8,
          solarradiation: 2,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['EPKT', 'EPKK', 'E6527'],
          source: 'obs',
        },
        {
          datetime: '02:00:00',
          datetimeEpoch: 1691625600,
          temp: 12.9,
          feelslike: 12.9,
          humidity: 93.74,
          dew: 11.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 12.2,
          windspeed: 9.2,
          winddir: 237,
          pressure: 1019,
          cloudcover: 26.2,
          visibility: 9.8,
          solarradiation: 2,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['EPKT', 'EPKK', 'E6527'],
          source: 'obs',
        },
        {
          datetime: '03:00:00',
          datetimeEpoch: 1691629200,
          temp: 12.9,
          feelslike: 12.9,
          humidity: 93.65,
          dew: 11.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 12.2,
          windspeed: 9.2,
          winddir: 252,
          pressure: 1020,
          cloudcover: 100,
          visibility: 9.8,
          solarradiation: 2,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: ['EPKT', 'EPKK', 'E6527'],
          source: 'obs',
        },
        {
          datetime: '04:00:00',
          datetimeEpoch: 1691632800,
          temp: 12.9,
          feelslike: 12.9,
          humidity: 93.74,
          dew: 11.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 11.9,
          windspeed: 5.3,
          winddir: 220,
          pressure: 1020,
          cloudcover: 100,
          visibility: 9.8,
          solarradiation: 2,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: ['EPKT', 'EPKK', 'E6527'],
          source: 'obs',
        },
        {
          datetime: '05:00:00',
          datetimeEpoch: 1691636400,
          temp: 11.9,
          feelslike: 11.9,
          humidity: 93.7,
          dew: 10.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 10.4,
          windspeed: 7.5,
          winddir: 270,
          pressure: 1020,
          cloudcover: 26.2,
          visibility: 9.8,
          solarradiation: 2,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['EPKT', 'EPKK', 'E6527'],
          source: 'obs',
        },
        {
          datetime: '06:00:00',
          datetimeEpoch: 1691640000,
          temp: 11.9,
          feelslike: 11.9,
          humidity: 87.75,
          dew: 10,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 8.3,
          windspeed: 5.3,
          winddir: 270,
          pressure: 1021,
          cloudcover: 50.8,
          visibility: 9.8,
          solarradiation: 41,
          solarenergy: 0.1,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['EPKT', 'EPKK', 'E6527'],
          source: 'obs',
        },
        {
          datetime: '07:00:00',
          datetimeEpoch: 1691643600,
          temp: 11.9,
          feelslike: 11.9,
          humidity: 93.7,
          dew: 10.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 7.9,
          windspeed: 9.3,
          winddir: 258,
          pressure: 1021,
          cloudcover: 88.2,
          visibility: 9.8,
          solarradiation: 361,
          solarenergy: 1.3,
          uvindex: 4,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['EPKT', 'EPKK', 'E6527'],
          source: 'obs',
        },
        {
          datetime: '08:00:00',
          datetimeEpoch: 1691647200,
          temp: 12.9,
          feelslike: 12.9,
          humidity: 87.84,
          dew: 11,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 11.9,
          windspeed: 3.6,
          winddir: 272.2,
          pressure: 1021,
          cloudcover: 88.2,
          visibility: 9.8,
          solarradiation: 456,
          solarenergy: 1.6,
          uvindex: 5,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['EPKT', 'EPKK', 'E6527'],
          source: 'obs',
        },
        {
          datetime: '09:00:00',
          datetimeEpoch: 1691650800,
          temp: 13.9,
          feelslike: 13.9,
          humidity: 87.84,
          dew: 12,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 12.6,
          windspeed: 5.4,
          winddir: 270,
          pressure: 1022,
          cloudcover: 50.8,
          visibility: 9.9,
          solarradiation: 676,
          solarenergy: 2.4,
          uvindex: 7,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['EPKT', 'EPKK', 'E6527'],
          source: 'obs',
        },
        {
          datetime: '10:00:00',
          datetimeEpoch: 1691654400,
          temp: 15.9,
          feelslike: 15.9,
          humidity: 72.51,
          dew: 11,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 10.8,
          windspeed: 5.4,
          winddir: 240,
          pressure: 1022,
          cloudcover: 50.6,
          visibility: 10,
          solarradiation: 1193,
          solarenergy: 4.3,
          uvindex: 10,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['EPKT', 'EPKK', 'E6527'],
          source: 'obs',
        },
        {
          datetime: '11:00:00',
          datetimeEpoch: 1691658000,
          temp: 18,
          feelslike: 18,
          humidity: 63.68,
          dew: 11,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 9.4,
          windspeed: 3.6,
          winddir: 17.1,
          pressure: 1022,
          cloudcover: 87.4,
          visibility: 10,
          solarradiation: 561,
          solarenergy: 2,
          uvindex: 6,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['EPKT', 'EPKK', 'E6527'],
          source: 'obs',
        },
        {
          datetime: '12:00:00',
          datetimeEpoch: 1691661600,
          temp: 18,
          feelslike: 18,
          humidity: 63.48,
          dew: 10.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 9.7,
          windspeed: 12.8,
          winddir: 270,
          pressure: 1022,
          cloudcover: 87.4,
          visibility: 10,
          solarradiation: 857,
          solarenergy: 3.1,
          uvindex: 9,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['EPKT', 'EPKK', 'E6527'],
          source: 'obs',
        },
        {
          datetime: '13:00:00',
          datetimeEpoch: 1691665200,
          temp: 18,
          feelslike: 18,
          humidity: 63.48,
          dew: 10.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 11.5,
          windspeed: 7.6,
          winddir: 330,
          pressure: 1022,
          cloudcover: 87,
          visibility: 10,
          solarradiation: 1137,
          solarenergy: 4.1,
          uvindex: 10,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['EPKT', 'EPKK', 'E6527'],
          source: 'obs',
        },
        {
          datetime: '14:00:00',
          datetimeEpoch: 1691668800,
          temp: 20,
          feelslike: 20,
          humidity: 52.42,
          dew: 9.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 11.9,
          windspeed: 7.5,
          winddir: 71.5,
          pressure: 1021,
          cloudcover: 50,
          visibility: 10,
          solarradiation: 1145,
          solarenergy: 4.1,
          uvindex: 10,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['EPKT', 'EPKK', 'E6527'],
          source: 'obs',
        },
        {
          datetime: '15:00:00',
          datetimeEpoch: 1691672400,
          temp: 20,
          feelslike: 20,
          humidity: 52.42,
          dew: 9.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 13,
          windspeed: 5.5,
          winddir: 350,
          pressure: 1021,
          cloudcover: 50,
          visibility: 10,
          solarradiation: 655,
          solarenergy: 2.4,
          uvindex: 7,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['E9997', 'EPKT', 'EPKK'],
          source: 'obs',
        },
        {
          datetime: '16:00:00',
          datetimeEpoch: 1691676000,
          temp: 20,
          feelslike: 20,
          humidity: 49.11,
          dew: 9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 12.6,
          windspeed: 5.5,
          winddir: 19,
          pressure: 1021,
          cloudcover: 50,
          visibility: 10,
          solarradiation: 813,
          solarenergy: 2.9,
          uvindex: 8,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['EPKT', 'EPKK', 'E6527'],
          source: 'obs',
        },
        {
          datetime: '17:00:00',
          datetimeEpoch: 1691679600,
          temp: 20,
          feelslike: 20,
          humidity: 49.01,
          dew: 8.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 11.9,
          windspeed: 5.5,
          winddir: 309,
          pressure: 1021,
          cloudcover: 50,
          visibility: 10,
          solarradiation: 424,
          solarenergy: 1.5,
          uvindex: 4,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['E9997', 'EPKT', 'EPKK'],
          source: 'obs',
        },
        {
          datetime: '18:00:00',
          datetimeEpoch: 1691683200,
          temp: 20.9,
          feelslike: 20.9,
          humidity: 46.17,
          dew: 8.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 13.7,
          windspeed: 7.5,
          winddir: 329,
          pressure: 1021,
          cloudcover: 25,
          visibility: 10,
          solarradiation: 1154,
          solarenergy: 4.2,
          uvindex: 10,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['EPKT', 'EPKK', 'E6527'],
          source: 'obs',
        },
        {
          datetime: '19:00:00',
          datetimeEpoch: 1691686800,
          temp: 20,
          feelslike: 20,
          humidity: 52.42,
          dew: 9.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 15.8,
          windspeed: 5.4,
          winddir: 291,
          pressure: 1021,
          cloudcover: 32.6,
          visibility: 10,
          solarradiation: 351,
          solarenergy: 1.3,
          uvindex: 4,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['EPKT', 'EPKK', 'E6527'],
          source: 'obs',
        },
        {
          datetime: '20:00:00',
          datetimeEpoch: 1691690400,
          temp: 16.2,
          feelslike: 16.2,
          humidity: 74.68,
          dew: 11.7,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 14.8,
          windspeed: 4,
          winddir: 139.1,
          pressure: 1021,
          cloudcover: 2.6,
          visibility: 24.1,
          solarradiation: 41,
          solarenergy: 0.1,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Clear',
          icon: 'clear-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '21:00:00',
          datetimeEpoch: 1691694000,
          temp: 14.7,
          feelslike: 14.7,
          humidity: 78.49,
          dew: 11,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 9.4,
          windspeed: 4,
          winddir: 142.7,
          pressure: 1022,
          cloudcover: 26.3,
          visibility: 24.1,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '22:00:00',
          datetimeEpoch: 1691697600,
          temp: 13.6,
          feelslike: 13.6,
          humidity: 82.63,
          dew: 10.7,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 8.3,
          windspeed: 4,
          winddir: 144.7,
          pressure: 1022,
          cloudcover: 87.2,
          visibility: 24.1,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '23:00:00',
          datetimeEpoch: 1691701200,
          temp: 12.8,
          feelslike: 12.8,
          humidity: 85.9,
          dew: 10.5,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 8.3,
          windspeed: 4,
          winddir: 150.7,
          pressure: 1022,
          cloudcover: 35.1,
          visibility: 24.1,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: null,
          source: 'fcst',
        },
      ],
    },
  ],
  alerts: [],
  stations: {
    EPKK: {
      distance: 9706,
      latitude: 50.08,
      longitude: 19.8,
      useCount: 0,
      id: 'EPKK',
      name: 'EPKK',
      quality: 50,
      contribution: 0,
    },
    EPKT: {
      distance: 76445,
      latitude: 50.47,
      longitude: 19.07,
      useCount: 0,
      id: 'EPKT',
      name: 'EPKT',
      quality: 50,
      contribution: 0,
    },
    E9997: {
      distance: 47019,
      latitude: 49.967,
      longitude: 20.574,
      useCount: 0,
      id: 'E9997',
      name: 'EW9997 Jasien PL',
      quality: 0,
      contribution: 0,
    },
    E6527: {
      distance: 10364,
      latitude: 50.153,
      longitude: 19.955,
      useCount: 0,
      id: 'E6527',
      name: 'EW6527 Krakow PL',
      quality: 0,
      contribution: 0,
    },
  },
  currentConditions: {
    datetime: '19:36:00',
    datetimeEpoch: 1691688960,
    temp: 19.9,
    feelslike: 19.9,
    humidity: 56,
    dew: 10.9,
    precip: 0,
    precipprob: 0,
    snow: 0,
    snowdepth: 0,
    preciptype: null,
    windgust: 0,
    windspeed: 2.8,
    winddir: 254,
    pressure: 1021,
    cloudcover: 2.6,
    visibility: 10,
    solarradiation: 41,
    solarenergy: 0.1,
    uvindex: 0,
    conditions: 'Clear',
    icon: 'clear-day',
    stations: ['E9997', 'EPKK', 'E6527'],
    source: 'obs',
    sunrise: '05:21:46',
    sunriseEpoch: 1691637706,
    sunset: '20:08:43',
    sunsetEpoch: 1691690923,
    moonphase: 0.8,
  },
};
